{
 "title": "Express App",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(http_request_duration_seconds_count, service)"
   }
  ]
 },
 "panels": [
  {
   "title": "Response Codes per Minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status_code, project_version)(rate(prometheus_http_request_duration_seconds_count[1m]))",
     "legendFormat": "HTTP {{status_code}} Versão {{project_version}}"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(prometheus_http_request_duration_seconds_sum[5m])) by (status_code, project_version)",
     "legendFormat": "HTTP {{status_code}} Versão {{project_version}}"
    }
   ]
  },
  {
   "title": "Requests Per Minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (method, path, project_version)(rate(prometheus_http_request_duration_seconds_count[1m]))",
     "legendFormat": "{{method}} {{path}} {{project_version}}"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(prometheus_http_request_duration_seconds_sum[5m])) by (method, path, project_version)",
     "legendFormat": "{{method}} {{path}} {{project_version}}"
    }
   ]
  }
 ]
}